sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

install:
    - wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
    - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb
    - sudo apt-get install flex bison libssl-dev
    - sudo apt-get install g++

script:
    - bazel build //:baikaldb
    - bazel build //:baikalStore
    - bazel build //:baikalMeta
    
